package cn.lcy.lookfor.model;
// Generated 2017-10-28 21:22:06 by Hibernate Tools 5.0.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PostRelease generated by hbm2java
 */
@Entity
@Table(name = "post_release", catalog = "lookfor")
public class PostRelease implements java.io.Serializable {

	private String identifyId;
	private User user;
	private Date releaseTime;
	private String title;
	private String content;
	private String description;
	private String reward;
	private Long viewCount;
	private Long uncoverCount;
	private Long successCount;
	private String paidMoney;
	private Integer status;
	private Set<PostView> postViews = new HashSet<PostView>(0);
	private Set<PostUncover> postUncovers = new HashSet<PostUncover>(0);

	public PostRelease() {
	}

	public PostRelease(String identifyId, User user, Date releaseTime, String title, String reward) {
		this.identifyId = identifyId;
		this.user = user;
		this.releaseTime = releaseTime;
		this.title = title;
		this.reward = reward;
	}

	public PostRelease(String identifyId, User user, Date releaseTime, String title, String content, String description,
			String reward, Long viewCount, Long uncoverCount, Long successCount, String paidMoney, Integer status,
			Set<PostView> postViews, Set<PostUncover> postUncovers) {
		this.identifyId = identifyId;
		this.user = user;
		this.releaseTime = releaseTime;
		this.title = title;
		this.content = content;
		this.description = description;
		this.reward = reward;
		this.viewCount = viewCount;
		this.uncoverCount = uncoverCount;
		this.successCount = successCount;
		this.paidMoney = paidMoney;
		this.status = status;
		this.postViews = postViews;
		this.postUncovers = postUncovers;
	}

	@Id

	@Column(name = "identify_id", unique = true, nullable = false, length = 10)
	public String getIdentifyId() {
		return this.identifyId;
	}

	public void setIdentifyId(String identifyId) {
		this.identifyId = identifyId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "release_user", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_time", nullable = false, length = 19)
	public Date getReleaseTime() {
		return this.releaseTime;
	}

	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}

	@Column(name = "title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "content", length = 200)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "reward", nullable = false, length = 10)
	public String getReward() {
		return this.reward;
	}

	public void setReward(String reward) {
		this.reward = reward;
	}

	@Column(name = "view_count")
	public Long getViewCount() {
		return this.viewCount;
	}

	public void setViewCount(Long viewCount) {
		this.viewCount = viewCount;
	}

	@Column(name = "uncover_count")
	public Long getUncoverCount() {
		return this.uncoverCount;
	}

	public void setUncoverCount(Long uncoverCount) {
		this.uncoverCount = uncoverCount;
	}

	@Column(name = "success_count")
	public Long getSuccessCount() {
		return this.successCount;
	}

	public void setSuccessCount(Long successCount) {
		this.successCount = successCount;
	}

	@Column(name = "paid_money", length = 10)
	public String getPaidMoney() {
		return this.paidMoney;
	}

	public void setPaidMoney(String paidMoney) {
		this.paidMoney = paidMoney;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postRelease")
	public Set<PostView> getPostViews() {
		return this.postViews;
	}

	public void setPostViews(Set<PostView> postViews) {
		this.postViews = postViews;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "postRelease")
	public Set<PostUncover> getPostUncovers() {
		return this.postUncovers;
	}

	public void setPostUncovers(Set<PostUncover> postUncovers) {
		this.postUncovers = postUncovers;
	}

}
