package cn.lcy.lookfor.model;
// Generated 2017-11-11 21:48:15 by Hibernate Tools 5.0.6.Final

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import javax.persistence.*;
import java.util.Date;

/**
 * PostView generated by hbm2java
 */
@Entity
@Table(name = "post_view", catalog = "lookfor")
@JsonIdentityInfo(generator = ObjectIdGenerators.StringIdGenerator.class, property = "@id")
public class PostView implements java.io.Serializable {

    private String identifyId;
    private PostRelease postRelease;
    private User user;
    private Date viewTime;

    public PostView() {
    }

    public PostView(String identifyId, PostRelease postRelease, User user, Date viewTime) {
        this.identifyId = identifyId;
        this.postRelease = postRelease;
        this.user = user;
        this.viewTime = viewTime;
    }

    @Id

    @Column(name = "identify_id", unique = true, nullable = false, length = 32)
    public String getIdentifyId() {
        return this.identifyId;
    }

    public void setIdentifyId(String identifyId) {
        this.identifyId = identifyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "view_post", nullable = false)
    public PostRelease getPostRelease() {
        return this.postRelease;
    }

    public void setPostRelease(PostRelease postRelease) {
        this.postRelease = postRelease;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "view_user", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "view_time", nullable = false, length = 19)
    public Date getViewTime() {
        return this.viewTime;
    }

    public void setViewTime(Date viewTime) {
        this.viewTime = viewTime;
    }

}
